#TODO: move/rename this file
services:
    pim_enrich.connector.use_cases.validator.get_list_of_products:
        class: Akeneo\Pim\Enrichment\Component\Product\Connector\UseCase\GetListOfProductsQueryValidator
        arguments:
            - '@pim_catalog.repository.cached_category'
            - '@pim_catalog.repository.cached_locale'
