parameters:
    pim_api.pagination.offset_hal_paginator.class: Akeneo\Tool\Component\Api\Pagination\OffsetHalPaginator
    pim_api.pagination.search_after_hal_paginator.class: Akeneo\Tool\Component\Api\Pagination\SearchAfterHalPaginator

services:
    pim_api.pagination.parameter_validator:
        class: 'Akeneo\Tool\Component\Api\Pagination\PaginationParametersValidator'
        arguments:
            - '%pim_api.configuration%'

    # TODO: to move
    pim_api.product.query_parameters_validator:
        class: 'Akeneo\Tool\Component\Api\Pagination\ProductParameterValidator'
        arguments:
            - '@pim_catalog.repository.cached_channel'
            - '@pim_api.pagination.parameter_validator'
            - '@pim_api.checker.query_parameters_product'

    pim_api.pagination.offset_hal_paginator:
        class: '%pim_api.pagination.offset_hal_paginator.class%'
        arguments:
            - '@router'

    pim_api.pagination.search_after_hal_paginator:
        class: '%pim_api.pagination.search_after_hal_paginator.class%'
        arguments:
            - '@router'
